menu:
    # Home: /
    Archive: /archives/
    # Tags: /tags/
    # Categories: /categories/
    About: /about/
    # Rss: /atom.xml
    Search: /search/

favicon: /favicon.ico
logo: /avatar.jpg

# Comment

gitalk:
  enable: true
  owner: allenfrostline
  repo: Comments-on-Whiteboard
  client_id: 8f880a91b82796d2ce14
  client_secret: dc2c450f9bd7fba631ce51de266a12684a729e89

# Analytics
ga: UA-93356635-1

# Copyright Infomation
startyear: 2016